name: Check Code Quality

on:
  push:
    branches-ignore:
      - "master"
  workflow_dispatch:

concurrency:
  group: check-code-quality
  cancel-in-progress: true

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install npm dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Run lint
        run: bun --filter "*" lint

      - name: Run type check
        run: bun --filter "*" check
