name: Deploy GitHub Pages

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

concurrency:
  group: deploy-github-pages
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install npm dependencies
        run: bun install

      - name: Build the deployable
        run: cd ./packages/main && bun run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: packages/main/build

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment